name: Bug report
description: File a bug report
title: [Bug] 
labels: ["Bug"]
body:
  - type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: operatingsys
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - Windows 10
        - Windows 11
        - Windows 7
        - Windows 8 / Windows 8.1
        - Debian-Based linux
        - Gentoo-Based linux [OpenRC]
        - Gentoo-Based linux [SystemD]
        - Arch-Based linux
        - MACOS [No current support]
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmation
      options:
        - label: I read the wiki and i am sure are depencies are installed!
        required: true